### ISSUE TITLE
#Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#166]
【现象】：越南毒蝎坦克的辐射对三星动员兵的伤害很低
【反馈人】：shuiping
【发现版本号】：G0615
【影响范围】：游戏平衡性
【产生原因】：未知

![GIF](https://user-images.githubusercontent.com/49360196/59969918-74db4d00-958c-11e9-94d1-87afed4de057.gif)

**Comment by Zero-Fanker** [comment]
@yuanbanlao kk怎么看这个问题------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月23日(星期天) 上午7:57
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166)



【现象】：越南毒蝎坦克的辐射对三星动员兵的伤害很低
 【反馈人】：shuiping
 【发现版本号】：G0615
 【影响范围】：游戏平衡性
 【产生原因】：未知
 

 
&mdash;

**Comment by shuiping233** [comment]
说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意

**Comment by Zero-Fanker** [comment]
喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午11:43
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166)



说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意
 
&mdash;

**Comment by shuiping233** [comment]
> 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午11:43 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

哇，那也太快了吧

**Comment by shuiping233** [comment]
> 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午11:43 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

回血速度已经和捡了医疗包差不多一样了哦

**Comment by Zero-Fanker** [comment]
没啥问题啊 受到攻击就会停止------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午12:18
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166)


 
喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
哇，那也太快了吧
 
&mdash;

**Comment by shuiping233** [comment]
> 没啥问题啊 受到攻击就会停止------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午12:18 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 哇，那也太快了吧 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
tql，那没问题就行了，反正动员兵输出不怎么样

**Comment by Zero-Fanker** [comment]
全局数据平衡要统筹考虑，你晚点在平衡性下面评论收集一下相关要素，例如对辐射的抵抗能力，升级之后的强化(火力 防护 速度 射程)等------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午12:21
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166)


 
没啥问题啊 受到攻击就会停止------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:18 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 哇，那也太快了吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
 tql，那没问题就行了，反正动员兵输出不怎么样
  
&mdash;

**Comment by shuiping233** [comment]
> 全局数据平衡要统筹考虑，你晚点在平衡性下面评论收集一下相关要素，例如对辐射的抵抗能力，升级之后的强化(火力 防护 速度 射程)等------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午12:21 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 没啥问题啊 受到攻击就会停止------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:18 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 哇，那也太快了吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. tql，那没问题就行了，反正动员兵输出不怎么样 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好，就在这里么？

**Comment by Zero-Fanker** [comment]
去内部事务里搜讨论------------------ 原始邮件 ------------------
发件人: "shuiping"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午12:24
收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>;
抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166)


 
全局数据平衡要统筹考虑，你晚点在平衡性下面评论收集一下相关要素，例如对辐射的抵抗能力，升级之后的强化(火力 防护 速度 射程)等------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:21 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 没啥问题啊 受到攻击就会停止------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:18 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 哇，那也太快了吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. tql，那没问题就行了，反正动员兵输出不怎么样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
好，就在这里么？
 
&mdash;

**Comment by shuiping233** [comment]
> 去内部事务里搜讨论------------------ 原始邮件 ------------------ 发件人: "shuiping"<notifications@github.com> 发送时间: 2019年6月28日(星期五) 中午12:24 收件人: "Zero-Fanker/RN_All_Issues"<RN_All_Issues@noreply.github.com>; 抄送: "Zero Fanker"<zcyfksn@vip.qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 全局数据平衡要统筹考虑，你晚点在平衡性下面评论收集一下相关要素，例如对辐射的抵抗能力，升级之后的强化(火力 防护 速度 射程)等------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:21 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 没啥问题啊 受到攻击就会停止------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午12:18 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 喘气回血是设定，往期更新应该有提过，也可能遗漏了，搜一下自述文档看看------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "shuiping"notifications@github.com 发送时间: 2019年6月28日(星期五) 中午11:43 收&#x4EF6;人: "Zero-Fanker/RN_All_Issues"RN_All_Issues@noreply.github.com; 抄送: "Zero Fanker"zcyfksn@vip.qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Zero-Fanker/RN_All_Issues] #Bug#越南毒蝎坦克的辐射对三星动员兵的伤害很低 (#166) 说一说另外的测试结果：三星海豹的抗辐射能力与三星动员兵类似（但是比三星动员兵差一些），还有一个风暴摩托也是。另外，三星动员兵有一个很奇妙的回血能力，在静止一段时间后能快速回满血量。但是并没有听到有关改动动员兵的消息。望注意 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 哇，那也太快了吧 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. tql，那没问题就行了，反正动员兵输出不怎么样 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 好，就在这里么？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好的，了解

**Comment by RN-Hydra** [comment]
三星动员兵有医院的情况跟上图一样，无医院伤害每次25，如果觉得数值过高可以降低医院回血或三星动员兵回血。

**Comment by shuiping233** [comment]
那就信你把
