### ISSUE TITLE
#bug#框选单位部署时，MCV无法展开

### ISSUE THREAD

**Issue by Suli1337** [Zero-Fanker/RN_All_Issues#582]
【现象】：框选单位部署时，MCV无法展开，但是美国大兵可以部署
【反馈人】：Suli
【发现版本号】：0.99.910
【影响范围】：玩家操作
【产生原因】：基地车部署有ROF？？
![image](https://user-images.githubusercontent.com/85695579/143667990-bfe521ec-3bd5-4cd0-8be9-03e14d181894.png)

**Comment by shuiping233** [comment]
此问题已有单子



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月27日(周六) 中午12:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Zero-Fanker/RN_All_Issues] 框选单位部署时，MCV无法展开 (Issue #582)




 
【现象】：框选单位部署时，MCV无法展开，但是美国大兵可以部署
 【反馈人】：Suli
 【发现版本号】：0.99.910
 【影响范围】：玩家操作
 【产生原因】：基地车部署有ROF？？
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zero-Fanker** [comment]
0.99.912a 已调整 @Renko-ji @shuiping233

**Comment by shuiping233** [comment]
？
昨天我忘记关这个单子了？
