### ISSUE TITLE
#Bug#遭遇战地图“黄金国Ⅱ”右上角瀑布地形未正常衔接

### ISSUE THREAD

**Issue by shuiping233** [Zero-Fanker/RN_All_Issues#838]
【现象】：如题，如图
【反馈人】：Mr.brain.evekin
【发现版本号】：0.99.913
【影响范围】：视觉体验
【产生原因】：未知

![image](https://user-images.githubusercontent.com/49360196/204073269-e5c97cb7-26cf-4a6d-9d18-7fce11f7674a.png)

**Comment by shuiping233** [comment]
鉴于考虑到瀑布周围的地形情况，修复难度较大，采用了去除此区域的瀑布的方案

**Comment by shuiping233** [comment]
0.99.916b2测试通过
![image](https://github.com/user-attachments/assets/7a02e3ed-14d9-4d50-9132-04fc30b53329)

**Comment by Zero-Fanker** [comment]
> 鉴于考虑到瀑布周围的地形情况，修复难度较大，采用了去除此区域的瀑布的方案 预期效果如下图所示 ![image](https://user-images.githubusercontent.com/49360196/204573077-11fe597d-6a9e-4de1-9aae-18d848533dec.png)

这个改动是不是很早之前就发布了？

**Comment by shuiping233** [comment]
> > 鉴于考虑到瀑布周围的地形情况，修复难度较大，采用了去除此区域的瀑布的方案 预期效果如下图所示 ![image](https://user-images.githubusercontent.com/49360196/204573077-11fe597d-6a9e-4de1-9aae-18d848533dec.png)
> 
> 这个改动是不是很早之前就发布了？

看图片的版本号,应该是的

**Comment by shuiping233** [comment]
> 那你去找到之前是跟着哪个版本出去的，把它归档啊
> […](#)

好吧

**Comment by shuiping233** [comment]
> 那你去找到之前是跟着哪个版本出去的，把它归档啊
> […](#)

我看了看,之前已经正确归档过了
![Image](https://github.com/user-attachments/assets/c72e0e66-3d64-4413-8936-563b2cae11f8)

**Comment by Zero-Fanker** [comment]
请你把它正确归档，该出现在更新日志的出现在日志里，单子该关的关掉



---Original---
From: ***@***.***&gt;
Sent at: 2025年3月20日(Thu) AM8:37
To: ***@***.***&gt;;
Cc: "Zero ***@***.******@***.***&gt;;
Subject: Re: [Zero-Fanker/RN_All_Issues] #Bug#遭遇战地图“黄金国Ⅱ”右上角瀑布地形未正常衔接 (Issue #838)


    
那你去找到之前是跟着哪个版本出去的，把它归档啊
 …
  
我看了看,之前已经正确归档过了
 image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  shuiping233 left a comment (Zero-Fanker/RN_All_Issues#838)
  
那你去找到之前是跟着哪个版本出去的，把它归档啊
 …
  
我看了看,之前已经正确归档过了
 image.png (view on web)
